### ISSUE TITLE
setBlock(pos,block)

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-world#2]
See https://github.com/JoeDoyle23/BurningPig/blob/master/terrain/terrain.js#L149

Seems doable to do the convertion pos -> chunk -> block

**Comment by wtfaremyinitials** [comment]
This *was* the plan all along. I just never got around to implementing it. :stuck_out_tongue:

**Comment by rom1504** [comment]
New more general issues there #3 and there #4
