### ISSUE TITLE
Defining the API

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-world#4]
I think prismarine-world should be providing an API similar to the [one](https://github.com/rom1504/prismarine-chunk/blob/use-prismarine-block/README.md#api) prismarine-chunk has.

Only difference is, prismarine-world would implement that API by transforming coordinates to get the correct chunk and then asking prismarine-chunk about doing the actual operation.

**Comment by rom1504** [comment]
I guess we'll probably need a setChunk and getChunk too.

**Comment by rom1504** [comment]
Done in #5

**Comment by wtfaremyinitials** [comment]
A lot of this is probably going to need to be async since not all of the world is going to be loaded at once.

**Comment by wtfaremyinitials** [comment]
Ex: Calling getBlock on an unloaded chunk won't be able to return right away

**Comment by rom1504** [comment]
Why would it need to be async ? Would generating chunks be done in an other threads or something like that ?

**Comment by rom1504** [comment]
Ah I guess you mean loading from a file might be async.

**Comment by wtfaremyinitials** [comment]
Loading from a file, generating chunks, both can/should be done asynchronously.

**Comment by rom1504** [comment]
Okay I guess it makes some sense, it would make the api harder to use and slower when the chunks are actually loaded though.
Should it work with callbacks ? (Or promise ? Since this is es6 and whatnot)

**Comment by wtfaremyinitials** [comment]
I think Promises is definitely the way to go. ES7 async await is the only way using this without driving yourself crazy.

**Comment by wtfaremyinitials** [comment]
And it won't be any slower, you would just call the callback immediately, synchronously.

**Comment by rom1504** [comment]
Ok, I'll change that in my PR.
And I think flying-squid might go es6 too, it'll make more sense.

**Comment by roblabla** [comment]
The way bukkit handles world, you cannot getBlock on an unloaded chunk. You first have to load it. I think we should have two functions : an async getBlock, and a fast "getBlockDirect", so people who do some heavy world editing don't get the slowness.

**Comment by wtfaremyinitials** [comment]
It won't be slow for already loaded chunks, because you can call the callback synchronously immediately.
@roblabla 
```js
async getBlockAt(x, y, z) {
    if(chunkIsLoaded(x, y, z))
         return getChunk(x, y).getBlock(x % 16, y, z % 16)
    else
         return await doAsyncStuffToLoadChunk().getBlock(x % 16, y, z % 16)
}
```

**Comment by roblabla** [comment]
Do not release the zalgo.

http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony

**Comment by wtfaremyinitials** [comment]
Alright ¯\_(ツ)_/¯

**Comment by rom1504** [comment]
Hmm does that mean we want to duplicate all these [methods](https://github.com/PrismarineJS/prismarine-world/pull/5/files#diff-04c6e90faac2675aa89e2176d2eec7d8R15) in `<method>` `<method>Sync` ?

**Comment by rom1504** [comment]
Should set* methods be async too ?

**Comment by rom1504** [comment]
Alright so I added all that stuff to my PR, it feels like stuff are duplicated, but I'm not sure we can do much better, if we figure that some sync method are useless later, we can still delete them.

**Comment by rom1504** [comment]
Is it really better to not do everything sync ? (for example : is loading a chunk slow enough that it should be done async ?)

**Comment by rom1504** [comment]
After some discussion with @roblabla , it's easier to just remove all the sync methods in prismarine-world.


The only problem with that is it makes it harder to generate stuff in memory without taking into account the chunks, but then it's a specific use-case that would need specific stuff done in the *Sync method (like creating  empty-chunk when needed), so I guess it could be done in an other repo when needed.

This will mean using Promise-all or some es7 equivalent there https://github.com/rom1504/prismarine-world/blob/implementation/example.js#L20

**Comment by rom1504** [comment]
done
