### ISSUE TITLE
World storage

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-world#7]
How should we do that ?
* vanilla-like : anvil format and all (how advanced is https://github.com/PrismarineJS/prismarine-provider-anvil ?)
* store it in something else (redis, sqlite,...) (see http://wiki.minetest.net/Database_backends for proof of feasibility)

**Comment by roblabla** [comment]
The default implementation should use something vanilla-like IMO. Obviously, care should be taken to make sure alternatives implementation using sqlite/redis/whatev is possible.

**Comment by rom1504** [comment]
vanilla is started, basic functionnality is there (see https://github.com/mhsjlw/flying-squid/pull/84)

Stuff are missing though, like metadata, see http://minecraft.gamepedia.com/Chunk_format to improve stuff

**Comment by dcbartlett** [comment]
I'd like to see this as portable as possible as well.  Don't want to have to go off and install a bunch of software just to be able to generate a world.  Perhaps handled by specific replace modules for the storage of the world.

My original thought was once the server is capable of running, seeing if a raspberry Pi could run it.  So, sqlite i'm a fan of for an *acceptable" experience.

**Comment by rom1504** [comment]
vanilla storage is implemented. We can open other issues when we want to talk about redis/sqlite/... backends.
